<a href="https://colab.research.google.com/github/masonproco/Face_Detect/blob/master/HW4/Question1_Question2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question 1



My answer assumes you're passing in lists, like how it was done in the posted test cases, and it only performs the operation on the first value.

I believe the professor said something about the depth being only 1 in one of his announcements as well.

Source: https://stackoverflow.com/questions/43086557/convolve2d-just-by-using-numpy

In [0]:
import numpy as np

def conv2d(input_mat, kernel_mat):

  inp = input_mat[0]
  kern = kernel_mat[0]

  filter_shape = tuple(np.subtract(inp.shape, kern.shape) + 1)

  strides = inp.strides + inp.strides

  sub_matrices = np.lib.stride_tricks.as_strided(inp, kern.shape + filter_shape, strides)

  m = np.einsum('ij,ijkl->kl', kern ,sub_matrices)

  return m


M is:
[[4]]


#Question 2
The same applies for question 1 as above. It assumes you're passing in a list and performs the operation on the matrix in the first position.

If the matrix is not a square matrix, the matrix is padded with 0's so the operation can commence.

Source: https://stackoverflow.com/questions/54962004/implement-max-mean-poolingwith-stride-with-numpy

In [0]:
import numpy as np

def maxpooling2d(input_mat, s):
  mat = input_mat[0]

  if (mat.shape[0] != mat.shape[1]):
  
      if (mat.shape[0] > mat.shape[1]):
        while (mat.shape[1] != mat.shape[0]):

          z = np.zeros((math.shape[0]), 1)
          mat = np.append(mat, z, 1)

      else:
        while(mat.shape[0] != mat.shape[1]):
          z = np.zeros((1, mat.shape[1]))

          mat = np.append(mat, z, 0)
  
  out_shape = ((mat.shape[0] - s)//2 + 1, (mat.shape[1] - s)//2 + 1)

  s_size = (s, s)

  Mat_w = np.lib.stride_tricks.as_strided(mat, shape = out_shape + s_size, strides = (2*mat.strides[0], 2*mat.strides[1]) + mat.strides)
  # print(Mat_w)
  Mat_w = Mat_w.reshape(-1, *s_size)

  return Mat_w.max(axis=(1,2)).reshape(out_shape)


[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
